name: Build Documentation

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_dir: ${{ steps.build.outputs.build_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install .[docs]

      - name: Build documentation
        id: build
        run: |
          cd docs
          sphinx-build -M html ./source ./build 
          echo "build_dir=$(pwd)/_build/html" >> $GITHUB_ENV
