name: Release Package To Pypi

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build the package
        run: |
          python -m build

      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-artifacts
          path: dist
          
  pypi-publish:
    name: upload release to PyPI

    environment:
      name: release

    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v3
        with:
          name: package-artifacts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: List files
        run: |
          ls -R

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1