name: Test Package

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          
      - name: Build the package
        run: |
          python -m build

      - name: Install the package
        run: |
          python -m pip install dist/*.whl
 
      - name: Install test dependencies
        run: |
          python -m pip install .[test]
          
      - name: Run tests
        run: |
          pytest
